@startuml
[TemplateVersionsRegions]-->[Regions]
[Invitations]-->[Users]
[BackendMachines]-->[Regions]
[WorkerCommands]-->[WorkerCommands]
[SharedNetworkNetAdapters]-->[Networks]
[TemplateVersionsRegions]-->[BackendMachines]
[Envs]-->[Users]
[Envs]-->[BackendEnvs]
[SharedNetworkNetAdapters]-->[NetAdapters]
[Courses]-->[Users]
[Requests]-->[TemplateVersionsRegions]
[UserOAuthAccessTokens]-->[Users]
[EnvTemplates]-->[Prototypes]
[UserFeatureViews]-->[Users]
[WebHookSubscriptions]-->[Users]
[BackendMachines]-->[BackendMachines]
[CourseStages]-->[Prototypes]
[Prototypes]-->[Users]
[CloudshareResourcesQuotas]-->[Contracts]
[BackendEnvPreparationAudits]-->[BackendEnvs]
[CloudshareResourcesQuotas]-->[Projects]
[NetAdapters]-->[Regions]
[Requests]-->[EnvRuns]
[ProjectPrototypes]-->[Prototypes]
[BackendMachines]-->[Machines]
[Requests]-->[BackendEnvs]
[ActionAudits]-->[Users]
[FastUploadFolders]-->[Users]
[ActionAudits]-->[Users]
[ViewerPages]-->[GuidedJourneys]
[BackendNotifications]-->[Requests]
[GuidedJourneySections]-->[GuidedJourneys]
[Requests]-->[MachineVanityNames]
[AudioVideoAttendees]-->[AudioVideoMeetings]
[GuidedJourneySectionProgresses]-->[GuidedJourneys]
[Requests]-->[MachineVanityNames]
[GuidedJourneySectionProgresses]-->[ViewerPages]
[Requests]-->[BackendEnvs]
[GuidedJourneySectionProgresses]-->[GuidedJourneySections]
[FinishedWelcomeTours]-->[Users]
[Requests]-->[BackendPrototypeEnvs]
[Invitations]-->[Users]
[Requests]-->[MachineInstanceTypes]
[GuidedJourneySections]-->[GuidedJourneyChapters]
[Checkpoints]-->[VVisionLearnRequests]
[ExternalCloudsCreateScripts]-->[ExternalClouds]
[SsoConnectors]-->[Contracts]
[GuidedJourneyChapters]-->[GuidedJourneys]
[CustomFieldValues]-->[CustomFieldDefinitions]
[Courses]-->[EnvironmentPolicies]
[ExternalCloudVms]-->[ExternalClouds]
[Courses]-->[SsoConnectors]
[ActionAudits]-->[EnvironmentPolicies]
[ExternalCloudCredentials]-->[ExternalClouds]
[Invitations]-->[EnvironmentPolicies]
[ActionAudits]-->[WebSessionAudits]
[ExternalResourcesEnvPrototypeVersions]-->[ExternalClouds]
[StorageSettingsProjects]-->[StorageSettings]
[EnvBillingOperations]-->[EnvironmentPolicies]
[AwsAccounts]-->[AwsAccountRuns]
[TransferJobs]-->[StorageSettings]
[SsoConnectors_Projects]-->[Projects]
[UsersProjects]-->[EnvironmentPolicies]
[AwsAccountRuns]-->[ExternalResourcesEnvPrototypeVersions]
[PrototypeVersionsRegions]-->[BackendPrototypeEnvs]
[SsoConnectors_Projects]-->[SsoConnectors]
[EnvironmentPolicies]-->[UsersProjects]
[EnvironmentPolicies]-->[Projects]
[Requests]-->[Courses]
[Envs]-->[Courses]
[Networks]-->[Regions]
[MachineScriptRuns]-->[BackendMachines]
[BackendEnvs]-->[Courses]
[Permalinks]-->[Regions]
[Students]-->[Courses]
[Invitations]-->[ClassSponsoredLinks]
[ExternalResourcesEnvPrototypeVersions]-->[Courses]
[BackendMachines]-->[IsoFiles]
[CustomFieldValues]-->[Courses]
[ActionAudits]-->[BackendMachines]
[CourseStages]-->[Courses]
[BackendMachines]-->[BackendMachines]
[Requests]-->[TemplateVersions]
[CloudshareIdentityVerificationMessages]-->[Users]
[Requests]-->[Regions]
[EnvUserRoles]-->[Envs]
[Requests]-->[BackendMachines]
[Requests]-->[Regions]
[EnvUserRoles]-->[Users]
[BackendEnvs]-->[Regions]
[Envs]-->[ProjectTeams]
[Courses]-->[ProjectTeams]
[ViewerPages]-->[ViewerCustomizations]
[ActionAudits]-->[FastUploadFolders]
[Invitations]-->[Envs]
[BackendPrototypeRegionConfigs]-->[Prototypes]
[Envs]-->[PrototypeVersions]
[FastUploadFolders]-->[BackendMachines]
[ExternalResourcesParameters]-->[Courses]
[Invitations]-->[EnvUserRoles]
[BackendPrototypeRegionConfigs]-->[Regions]
[Envs]-->[PrototypeVersions]
[FastUploadFolders]-->[BackendMachines]
[ExternalResourcesParameters]-->[Invitations]
[BackendNotifications]-->[IsoFiles]
[Requests]-->[Machines]
[PrototypeVersions]-->[PrototypeVersions]
[UsersProjectsDefaultTeams]-->[Users]
[BackendNotifications]-->[Requests]
[PrototypeVersions]-->[PrototypeVersions]
[UsersProjectsDefaultTeams]-->[Projects]
[ActionAudits]-->[Courses]
[UsersProjectsDefaultTeams]-->[ProjectTeams]
[Requests]-->[Requests]
[UserFavorites]-->[Users]
[UserEnvStudents]-->[Users]
[Prototypes]-->[ProjectPrototypes]
[ActionAudits]-->[BackendMachines]
[ContentFolders]-->[Users]
[UserEnvStudents]-->[Envs]
[Users]-->[UsersProjects]
[Prototypes]-->[PrototypeVersions]
[ContentFolders]-->[Projects]
[TransferJobsCloudStorageCopyRequests]-->[TransferJobs]
[StorageSettingsProjects]-->[Projects]
[UserEnvStudents]-->[Students]
[ActionAudits]-->[ProjectPrototypes]
[ContentFolderMemberships]-->[Envs]
[EndUserLoginCustomizations]-->[ViewerCustomizations]
[Invitations]-->[ProjectTeams]
[TransferJobs]-->[Users]
[ActionAudits]-->[UsersProjects]
[Requests]-->[Prototypes]
[TransferJobs]-->[Requests]
[MachineVanityNames]-->[Machines]
[ActionAudits]-->[Projects]
[Permalinks]-->[Projects]
[Invitations]-->[UsersProjects]
[ProjectTeams]-->[Projects]
[Permalinks]-->[EnvironmentPolicies]
[CustomEmails]-->[Projects]
[Contracts_Projects]-->[Projects]
[Invitations]-->[Envs]
[Permalinks]-->[PrototypeVersions]
[Requests]-->[Requests]
[Requests]-->[BackendEnvs]
[Invitations]-->[ProjectPrototypes]
[TransferJobsCloudStorageCopyRequests]-->[Requests]
[TransferJobsCloudStorageCopyRequests]-->[Users]
[EnvOperationAudits]-->[Requests]
[Invitations]-->[UsersProjects]
[EnvOperationAudits]-->[Machines]
[UsersProjects]-->[ProjectPrototypes]
[ClassSponsoredLinks]-->[Courses]
[EnvOperationAudits]-->[Requests]
[ProjectPrototypes]-->[Projects]
[ExternalResourcesEnvPrototypeVersions]-->[AwsAccountRuns]
[Contracts]-->[LmsIntegrations]
[BackendMachines]-->[BackendMachines]
[Envs]-->[Prototypes]
[UsersProjects]-->[Projects]
[ExternalResourcesEnvPrototypeVersions]-->[AwsAccounts]
[Invitations]-->[Prototypes]
[Contracts]-->[AwsAccountPools]
[Students]-->[CourseStages]
[BackendMachines]-->[BackendMachineGroups]
[AwsAccounts]-->[AwsAccountPools]
[Invitations]-->[UsersProjects]
[SharedEnvMemberships]-->[Envs]
[BackendMachineGroups]-->[Prototypes]
[SharedEnvMemberships]-->[Networks]
[CourseMeetings]-->[Courses]
[MachineDomains]-->[BackendMachines]
[VmImports]-->[Projects]
[MachineUsers]-->[BackendMachines]
[SharedEnvMemSubEnvs]-->[Envs]
[SlackWebhooks]-->[Users]
[VmImports]-->[PrototypeVersions]
[WorkerCommands]-->[ExternalResourcesEnvPrototypeVersions]
[SlackWebhooks]-->[Courses]
[VmImports]-->[Requests]
[ActionAudits]-->[ExternalResourcesEnvPrototypeVersions]
[Requests]-->[Projects]
[ContentFolderMemberships]-->[ContentFolders]
[VmImports]-->[Users]
[ExternalCloudVms]-->[ExternalResourcesEnvPrototypeVersions]
[PipelinesInstances]-->[StagesInstances]
[Requests]-->[ContentFolderMemberships]
[Contracts]-->[ContractsTerms]
[BackendEnvs]-->[BackendPrototypeEnvs]
[Requests]-->[ContentFolderMemberships]
[Instructors]-->[Courses]
[PrototypeVersions]-->[BackendPrototypeEnvs]
[Instructors]-->[UsersProjects]
[CustomFieldDefinitions]-->[TrainingSettings]
[Courses]-->[Instructors]
[CourseRegions]-->[Courses]
[Students]-->[Envs]
[Projects]-->[TrainingSettings]
[ProjectIpRestrictions]-->[ProjectsFlags]
[CourseRegions]-->[Regions]
[LtiConfigurations]-->[Courses]
[Projects]-->[ProjectsFlags]
[Courses]-->[Courses]
[Envs]-->[EnvironmentPolicies]
[ActionAudits]-->[Users]
[EnvOperationAudits]-->[Requests]
[EnvRuns]-->[Envs]
[Contracts_Users]-->[Users]
[EnvOperationAudits]-->[Envs]
[BackendEnvs]-->[Envs]
[PrototypeVersions]-->[Envs]
[EnvOperationAudits]-->[PrototypeVersions]
[Requests]-->[Regions]
[ExternalCloudsCreateScripts]-->[Projects]
[MachineUsers]-->[MachineDomains]
[Requests]-->[BackendMachines]
[EnvResourceAudits]-->[Envs]
[ExternalResourcesEnvPrototypeVersions]-->[Envs]
[BackendMachines]-->[MachineDomains]
[Envs]-->[UsersProjects]
[Invitations]-->[Envs]
[ExternalResourcesEnvPrototypeVersions]-->[PrototypeVersions]
[Requests]-->[Prototypes]
[EnvBillingOperations]-->[Envs]
[ExternalCloudsCreateScripts]-->[Projects]
[Invitations]-->[ProjectTeams]
[Requests]-->[Envs]
[ProjectsFeatureFlags]-->[Projects]
[BackendEnvPreparationAudits]-->[EnvRuns]
[WebSessionAudits]-->[WebSessionAudits]
[Machines]-->[Envs]
[ActionAudits]-->[Users]
[Machines]-->[PrototypeVersions]
[IsoFiles]-->[Users]
[ActionAudits]-->[Users]
[Machines]-->[BackendMachines]
[BackendNotifications]-->[Requests]
[Courses]-->[Regions]
[Requests]-->[Requests]
[Invitations]-->[Regions]
[Requests]-->[BackendMachines]
[Projects]-->[Contracts]
[IsoFiles_Projects]-->[Projects]
[ActionAudits]-->[Students]
[Requests]-->[Machines]
[BackendMachineRegionAmis]-->[BackendMachines]
[IsoFiles_Projects]-->[IsoFiles]
[NetAdapters]-->[Networks]
[Requests]-->[BackendEnvs]
[BackendMachineRegionAmis]-->[Regions]
[WorkerCommands]-->[ExternalCloudsCreateScripts]
[NetAdapters]-->[BackendMachines]
[ExternalResourcesEnvPrototypeVersions]-->[ExternalCloudsCreateScripts]
[Networks]-->[BackendMachineGroups]
[IsoFileRegions]-->[IsoFiles]
[Networks]-->[Networks]
[IsoFileRegions]-->[Regions]
[SponsoredEnvTokens]-->[Envs]
[PrototypeVersionsRegions]-->[PrototypeVersions]
[GuestOsIdentifiers]-->[OsFamilies]
[Envs]-->[EnvRuns]
[UsersProjects]-->[UsersProjects]
[PrototypeVersionsRegions]-->[Regions]
[GuestOsIdentifiers]-->[VmwareApiVersions]
[PrototypeVersions]-->[Prototypes]
[Pipelines]-->[Projects]
[Requests]-->[Users]
[Pipelines]-->[Users]
[PipelinesInstances]-->[Pipelines]
[Requests]-->[BackendMachines]
[BackendEnvs]-->[BackendMachineGroups]
[PipelinesInstances]-->[Users]
[UserNotifications]-->[Requests]
[ActionAudits]-->[Envs]
[Stages]-->[Pipelines]
[StagesInstances]-->[PipelinesInstances]
[Requests]-->[PrototypeVersionsRegions]
[SharedEnvMemSubEnvs]-->[SharedEnvMemberships]
[StagesInstances]-->[Stages]
[Machines]-->[Requests]
[BackendPrototypeEnvs]-->[BackendMachineGroups]
[Projects]-->[SharedEnvMemberships]
[ExternalResourcesQuotas]-->[Projects]
[StagesInstances]-->[Users]
[Requests]-->[IsoFiles]
[Jobs]-->[Stages]
[EnvOperationAudits]-->[WebSessionAudits]
[Jobs]-->[JobTypes]
[Contracts_Projects]-->[Contracts]
[EnvRuns]-->[WebSessionAudits]
[DeprovisionSteps]-->[Contracts]
[RemoteAccessSettings]-->[Users]
[ExternalResourcesQuotas]-->[Contracts]
[Projects]-->[Users]
[ActionAudits]-->[Contracts]
[JobTypesParameters]-->[JobTypes]
[ExternalCloudCredentials]-->[Contracts]
[BackendMachines]-->[BackendMachines]
[Contracts_Users]-->[Contracts]
[MachineScriptRuns]-->[Machines]
[Machines]-->[Requests]
[ABtestResults]-->[Users]
[EndUsersAccessPermissions]-->[Courses]
[EndUsersAccessPermissions]-->[Projects]
[Requests]-->[PrototypeVersions]
[UsersProjects]-->[ProjectTeams]
[Requests]-->[PrototypeVersions]
[UserNotifications]-->[Users]
[Envs]-->[WebSessionAudits]
[Requests]-->[PrototypeVersions]
[Requests]-->[Requests]
[WebSessionAudits]-->[Users]
[UserNotifications]-->[Requests]
[PrototypeVersions]-->[Users]
[WorkerCommands]-->[ExternalCloudCredentials]
[GuidedJourneySections]-->[Checkpoints]
[Templates]-->[TemplateVersions]
[EditMachineOperationsAdditionalData]-->[EnvOperationAudits]
[Courses]-->[Prototypes]
[TemplateVersions]-->[Templates]
[TemplateVersions]-->[BackendMachines]
[Requests]-->[MachineScriptRuns]
[UsersProjects]-->[Users]
[BackendMachines]-->[TemplateVersions]
[DeleteEnvRequests]-->[Envs]
[TemplateVersionsRegions]-->[TemplateVersions]
[Envs]-->[Regions]
@enduml